version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    network_mode: "host"
    environment:
      POSTGRES_DB: cloudcontrol
      POSTGRES_USER: cloudcontrol_user
      POSTGRES_PASSWORD: cloudcontrol2024
    volumes:
      - sitechime_pgdata:/var/lib/postgresql/data
    command: -p 5434

  web:
    build: .
    network_mode: "host"
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env

volumes:
  sitechime_pgdata:
