# Generated by Django 5.1.6 on 2025-03-04 12:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondata',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this data is publicly accessible via UUID'),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID for public access to this data', unique=True),
        ),
    ]
