# Generated by Django 5.1.7 on 2025-03-26 07:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jsondata_is_public_jsondata_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TncAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.CharField(help_text='Configuration ID associated with the TnC', max_length=255)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the user who accepted the TnC')),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the browser/client', null=True)),
            ],
            options={
                'verbose_name': 'TnC Acceptance',
                'verbose_name_plural': 'TnC Acceptances',
                'ordering': ['-accepted_at'],
            },
        ),
    ]
